(** Representation of SlotMachine.

    The SlotMachine module provides a simulation of a slot machine game  
    It defines necessary types for representing synbols and slotmachine and
    functions for spinning a slotmachine, printing a slotmachine, checking
    whether the spin is a win. *)

(**********************************************************************
 **********************************************************************)

type symbol = string
(** The type [symbol] represents a symbol on a slot machine reel. *)

type slot_machine = symbol list list
(** The type [slot_machine] represents a slot machine, which is composed of 
    multiple reels, each containing a list of symbols. *)

val spin_slot_machine : unit -> symbol list
(** [spin_slot_machine ()] simulates a spin of the slot machine and returns a 
    list of symbols generated by each reel. *)

val print_spin_result : symbol list -> unit
(** [print_spin_result result] prints the result of a slot machine spin. The 
    [result] parameter is a list of symbols generated by each reel. *)

val main : unit -> unit
(** [main ()] simulates a spin of the slot machine and prints the result. *)

val is_win : symbol list -> bool
(** [is_win result] checks if the given slot machine spin result is a win. The 
    [result] parameter is a list of symbols generated by each reel. *)
